# flask-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: farhanahmed3/flask-mongodb-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: flask-mongo-secrets
              key: MONGODB_URI
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: flask-mongo-secrets
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-mongo-secrets
              key: MONGODB_PASSWORD
        - name: FLASK_RUN_HOST
          valueFrom:
            secretKeyRef:
              name: flask-mongo-secrets
              key: FLASK_RUN_HOST
        - name: FLASK_RUN_PORT
          valueFrom:
            secretKeyRef:
              name: flask-mongo-secrets
              key: FLASK_RUN_PORT
        resources:
          requests:
            memory: "250Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "500m"
